disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Brady Price"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
   logo = "GREASE_LOGO_110_x_110.png.webp"
   secondaryLogo = "img/secondary-logo.png"
   description = "My awesome website by BP"
   copyright = "Copy, 2024 Brady Price, All Rights Reserved"

 [params.author]
   name = "BradyPrice"
   email = "bradyprice1@gmail.com"
    image = "img/GREASE_LOGO_110_x_110.png.webp"
   imageQuality = 96
   headline = "I'm only human"
   bio = "I live to farm"
  links = [
    
     { instagram = "https://instagram.com/organic_innovations" },
     { link = "https://growwithgrease.com/" },
  ]